/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 98tae
 */
public class Bai2 extends javax.swing.JFrame {

    Connection cn;
    ArrayList<HocSinh> listHocSinh;
    int index;

    /**
     * Creates new form Test
     */
    public Bai2() {
        initComponents();
        Clear_form();
        setLocationRelativeTo(null);
        cn = LHelper.ketNoi("Lab5_SOF203");
        listHocSinh = new ArrayList<>();
        if (cn != null) {
            LoadDatatoList();
            if (listHocSinh.size() > 0) {
                index = 0;
                showDetail();
            }
        } else {
            System.out.println("lỗi");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMAHS = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtDiemTb = new javax.swing.JTextField();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        btnADD = new javax.swing.JButton();
        btndElete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btlLast = new javax.swing.JButton();
        lblHienTai = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã HS");

        jLabel2.setText("Tên");

        jLabel3.setText("Gt");

        jLabel4.setText("DiemTB");

        buttonGroup1.add(radioNam);
        radioNam.setText("Nam");

        buttonGroup1.add(radioNu);
        radioNu.setText("Nữ");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnADD.setText("add");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        btndElete.setText("delete");
        btndElete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndEleteActionPerformed(evt);
            }
        });

        btnEdit.setText("edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btlLast.setText(">>");
        btlLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlLastActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDiemTb))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(43, 43, 43)
                                    .addComponent(radioNam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioNu))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMAHS, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndElete)
                            .addComponent(jButton1)
                            .addComponent(btnADD)
                            .addComponent(btnEdit)
                            .addComponent(btnTimKiem))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btlLast)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnADD, btnEdit, btndElete, jButton1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMAHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnADD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioNam)
                        .addComponent(radioNu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndElete)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDiemTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)))
                .addGap(27, 27, 27)
                .addComponent(btnTimKiem)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(btlLast)
                    .addComponent(lblHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnADD, btnEdit, btndElete, jButton1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try {
            if (index > 0) {
                index = 0;
                showDetail();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btlLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlLastActionPerformed
        try {
            if (index < listHocSinh.size() - 1) {
                index = listHocSinh.size() - 1;
                showDetail();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btlLastActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (index < listHocSinh.size() - 1) {
                index++;
                showDetail();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        if (txtTen.getText().equals("") | txtDiemTb.getText().equals("") | txtMAHS.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "VUi Long Khong De Trong Thong Tin");
            return;
        }
        try {
            String mahs = txtMAHS.getText();
            String tenhs = txtTen.getText();
            double diem = Double.parseDouble(txtDiemTb.getText());
            String GioiTinh = radioNam.isSelected() ? "Nam" : "Nữ";

            listHocSinh.add(new HocSinh(mahs, tenhs, GioiTinh, diem));

            String sql = "insert into HOCSINH(MaHS,TenHS,GioiTinh,DiemTB)\n"
                    + "values(?,?,?,?)";
            PreparedStatement pstm = cn.prepareStatement(sql);
            pstm.setString(1, mahs);
            pstm.setString(2, tenhs);
            pstm.setString(3, GioiTinh);
            pstm.setDouble(4, diem);

            if (pstm.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "thêm thành công");
            }
            index = listHocSinh.size() - 1;
            showDetail();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi add");
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            String mahs = txtMAHS.getText();
            String tenhs = txtTen.getText();
            double diem = Double.parseDouble(txtDiemTb.getText());
            String GioiTinh = radioNam.isSelected() ? "Nam" : "Nữ";
            listHocSinh.set(index, new HocSinh(mahs, tenhs, GioiTinh, diem));
            String sql = "update HOCSINH\n"
                    + "set TenHS =?, GioiTinh=?, DiemTB=?\n"
                    + "where MaHS=?";
            PreparedStatement pstm = cn.prepareStatement(sql);
            pstm.setString(1, tenhs);
            pstm.setString(2, GioiTinh);
            pstm.setDouble(3, diem);
            pstm.setString(4, mahs);
            if (pstm.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "thêm thành công");
            }
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi add");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (index > 0) {
                index--;
                showDetail();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Clear_form();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btndEleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndEleteActionPerformed
        if (txtMAHS.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "nhap ma sv");
            txtMAHS.requestFocus();
            return;
        }
        try {
            String mahs = txtMAHS.getText();
            listHocSinh.remove(index);
            String sql = "delete from HOCSINH \n"
                    + "where MaHS =?";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1,mahs);
            ps.execute();
//            if (ps.executeUpdate() > 0) {
//                JOptionPane.showMessageDialog(this, "thanh cong");
//            }
            if (index > 1) {
                index--;
            } else {
                index++;
            }
            showDetail();
            ps.close();
        } catch (Exception e) {
            System.out.println("Lỗi");
            e.printStackTrace();
        }


    }//GEN-LAST:event_btndEleteActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        
        for (int i = 0; i < listHocSinh.size(); i++) {
             HocSinh hs = listHocSinh.get(i);
            if (txtMAHS.getText().equals(hs.getMaHS())) {
             txtDiemTb.setText(String.valueOf(hs.getDiemTB()));
             txtTen.setText(hs.getTenHS());
                if (hs.getGioiTinh().equalsIgnoreCase("Nam")) {
                    radioNam.setSelected(true);
                }else{
                    radioNu.setSelected(true);
                }
                return;
           }
            
        }
        
         JOptionPane.showMessageDialog(this, "Không có Mã SV cần tìm");
    }//GEN-LAST:event_btnTimKiemActionPerformed

    public void Clear_form() {
        txtDiemTb.setText("");
        txtMAHS.setText("");
        txtTen.setText("");
        radioNam.setSelected(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlLast;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btndElete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblHienTai;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JTextField txtDiemTb;
    private javax.swing.JTextField txtMAHS;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

    private void LoadDatatoList() {
        try {
            String sql = "Select * From HOCSINH";
            Statement stm = cn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                listHocSinh.add(new HocSinh(rs.getString(1), rs.getString(2), rs.getString(3), rs.getDouble(4)));
            }
            stm.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showDetail() {
        HocSinh hs = listHocSinh.get(index);
        txtTen.setText(hs.getTenHS());
        txtMAHS.setText(hs.getMaHS());
        txtDiemTb.setText(String.valueOf(hs.getDiemTB()));
        if (hs.getGioiTinh().equalsIgnoreCase("nam")) {
            radioNam.setSelected(true);
        } else {
            radioNu.setSelected(true);
        }
        lblHienTai.setText(String.valueOf(index + 1));

    }
}
