/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI2;

import slide.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 98tae
 */
public class Form1 extends javax.swing.JFrame {

    Connection con;
     DefaultComboBoxModel<KhoaHoc> modelCombo = new DefaultComboBoxModel<>();

    /**
     * Creates new form baitest2
     */
    public Form1() {
        initComponents();
        setLocationRelativeTo(null);
        con = slide6.LHelper.ketNoi("LT6C");
        modelCombo = (DefaultComboBoxModel)cbbmonhoc.getModel();
        if (con != null) {
            LoadDataToCBB();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbbmonhoc = new javax.swing.JComboBox<>();
        lbmonhoc = new javax.swing.JLabel();
        btnMoForm2 = new javax.swing.JButton();
        btnForm3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Khóa Học");

        cbbmonhoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbmonhocItemStateChanged(evt);
            }
        });

        btnMoForm2.setText("Form 2");
        btnMoForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoForm2ActionPerformed(evt);
            }
        });

        btnForm3.setText("Form 3");
        btnForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForm3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(cbbmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(lbmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMoForm2)
                .addGap(18, 18, 18)
                .addComponent(btnForm3)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbbmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoForm2)
                    .addComponent(btnForm3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbmonhocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbmonhocItemStateChanged
        try {
            KhoaHoc kh = (KhoaHoc) cbbmonhoc.getSelectedItem();
            lbmonhoc.setText(kh.getTenKH());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbbmonhocItemStateChanged

    private void btnMoForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoForm2ActionPerformed
         KhoaHoc kh = (KhoaHoc) cbbmonhoc.getSelectedItem();
         new Form2(kh).setVisible(true);
    }//GEN-LAST:event_btnMoForm2ActionPerformed

    private void btnForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForm3ActionPerformed
       KhoaHoc kh = (KhoaHoc) cbbmonhoc.getSelectedItem();
       new Form3(kh.getMaKH(), kh.getTenKH(), kh.getHocPhi(), kh.getThoiLuong()).setVisible(true);
    }//GEN-LAST:event_btnForm3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForm3;
    private javax.swing.JButton btnMoForm2;
    private javax.swing.JComboBox<String> cbbmonhoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbmonhoc;
    // End of variables declaration//GEN-END:variables

 
    private void LoadDataToCBB() {
        try {
            String sql = "select * from KhoaHoc";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {     
                modelCombo.addElement(new KhoaHoc(rs.getString(1), rs.getString(2), rs.getDouble(3), rs.getInt(4)));
            }
        } catch (Exception e) {
        }
    }
}
