/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 98tae
 */
public class DSSV extends javax.swing.JFrame {
        DefaultTableModel dtm ;
        DefaultTableModel dtm2 ;
        Connection con;
    /**
     * Creates new form DSSV
     */
    public DSSV() {
        initComponents();
        setLocationRelativeTo(null);
        dtm = (DefaultTableModel) tblDSSV.getModel();
        dtm2 = (DefaultTableModel) tblQLDIEM.getModel();
        con = Helper.Helper_Connection.Connec();
        if (con != null) {
           LoadDataToTable();
            LoadDataToTable2(); 
        }
            
           setTitle("Danh Sách Sinh Viên Hiện Có");
           setDefaultCloseOperation(DISPOSE_ON_CLOSE);
           

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSSV = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLDIEM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDSSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MASV", "HoTen", "Email", "SoDT", "GioiTinh", "DiaChi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDSSV);

        jTabbedPane1.addTab("DSSV", jScrollPane2);

        tblQLDIEM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ Tên", "Tiếng Anh", "Tin Học", "GDTC", "Điểm TB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQLDIEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLDIEMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLDIEM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Điểm", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblQLDIEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLDIEMMouseClicked
       
    }//GEN-LAST:event_tblQLDIEMMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DSSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DSSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DSSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DSSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DSSV().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDSSV;
    private javax.swing.JTable tblQLDIEM;
    // End of variables declaration//GEN-END:variables

private void LoadDataToTable() {
        String gt = "";
    try {
           
            String sql = "select * from STUDENTS";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            dtm.setRowCount(0);
            while (rs.next()) {
                if (rs.getInt("GioiTinh") == 0) {
                    gt = "Nam";
                } else {
                    gt = "Nữ";
                }
                Object[] rowData = new Object[]{
                    rs.getString("MASV"),
                    rs.getString("Hoten"),
                    rs.getString("Email"),
                    rs.getString("SoDT"),
                    gt,
                    rs.getString("DiaChi"),
                    };
                dtm.addRow(rowData);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void LoadDataToTable2() {
        try {
            String sql = "Select (Tienganh+GDTC+Tinhoc)/3 as 'DTB',STUDENTS.MASV,Hoten,Tienganh,Tinhoc,GDTC  \n"
                    + "from GRADE join STUDENTS on GRADE.MASV = STUDENTS.MASV";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            dtm2.setRowCount(0);
            while (rs.next()) {
                double dtb = Math.ceil(rs.getDouble("DTB"));
                Object[] rowData = new Object[]{
                    rs.getString("MASV"),
                    rs.getString("Hoten"),
                    rs.getDouble("Tienganh"),
                    rs.getDouble("Tinhoc"),
                    rs.getDouble("GDTC"),
                    dtb,};
                dtm2.addRow(rowData);
            }
            stm.close();
            rs.close();
        } catch (Exception e) {
        }
    }


}
