/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitest2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 98tae
 */
public class FormMain extends javax.swing.JFrame {
    public static String MaHV,MaKH;
    public static Double Diem;
    Form2 form2 ;
    Connection con;
    DefaultTableModel dtm;
    DefaultComboBoxModel<String> cbbmodel;

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        con = Helper_Connection.Connec("LT6C");
        setLocationRelativeTo(null);
        dtm = (DefaultTableModel) tblmainfrom.getModel();
        cbbmodel = (DefaultComboBoxModel<String>) cbbmainForm.getModel();
        form2 = new Form2();
        if (con != null) {
            LoadDataToCBB();
            LoadDataToTable((String) cbbmodel.getSelectedItem());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbmainForm = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmainfrom = new javax.swing.JTable();
        btngoiForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbbmainForm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbmainFormItemStateChanged(evt);
            }
        });

        tblmainfrom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HV", "Mã KH", "Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmainfrom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmainfromMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmainfrom);

        btngoiForm.setText("Gọi Form");
        btngoiForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoiFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(cbbmainForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btngoiForm)
                .addGap(297, 297, 297))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(cbbmainForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btngoiForm)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbmainFormItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbmainFormItemStateChanged
        LoadDataToTable((String) cbbmodel.getSelectedItem());
    }//GEN-LAST:event_cbbmainFormItemStateChanged

    private void btngoiFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoiFormActionPerformed
       int viTri = tblmainfrom.getSelectedRow();
        if (viTri < 0 ){
            return;
        }
        if (form2.isVisible()) {
            return;
        }
        form2.setVisible(true);
    }//GEN-LAST:event_btngoiFormActionPerformed

    private void tblmainfromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmainfromMouseClicked
        int viTri = tblmainfrom.getSelectedRow();
        if (viTri < 0 ){
            return;
        }
        MaHV = String.valueOf(dtm.getValueAt(viTri, 0));
        MaKH = String.valueOf(dtm.getValueAt(viTri, 1));
        Diem =(Double) dtm.getValueAt(viTri, 2);
    }//GEN-LAST:event_tblmainfromMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngoiForm;
    public static javax.swing.JComboBox<String> cbbmainForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmainfrom;
    // End of variables declaration//GEN-END:variables

    private void LoadDataToCBB() {
        String sql = " SELECT TOP (1000) [MaKH]\n"
                + "      ,[TenKH]\n"
                + "      ,[HocPhi]\n"
                + "      ,[ThoiLuong]\n"
                + "  FROM [LT6C].[dbo].[KhoaHoc]";
        try {
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                cbbmodel.addElement(rs.getString("MaKH"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LoadDataToTable(String MaHV) {
        String sql = "SELECT TOP (1000) [MaHV]\n"
                + "      ,[MaKH]\n"
                + "      ,[Diem]\n"
                + "  FROM [LT6C].[dbo].[HocVien]\n"
                + "  Where MaKH = ?";
        try {
            PreparedStatement ptrs = con.prepareStatement(sql);
            ptrs.setString(1, MaHV);
            ResultSet rs = ptrs.executeQuery();
            dtm.setRowCount(0);
            while (rs.next()) {                
                Object[] rowData = new Object[]{
                rs.getString(1),
                    rs.getString(2),
                    rs.getDouble(3)
                };
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
